services:
  - type: web
    name: hoshiyaar-frontend
    env: node
    buildCommand: npm install && npm run build:spa
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE
        value: https://hoshiyaar-backend.onrender.com
